### ISSUE TITLE
add the plateau line option

### ISSUE THREAD

**Issue by HG14** [WedersonCD/customBarChart#3]
I make a try to add the plateau line 
in properties.js
line 223, i add  
                    Step: {
                        ref: "qDef.step",
                        label: "step",
                        type: "string",
                        component: "dropdown",
                        defaultValue: '',
                        options: [{ value: "", label: "" }, { value: "start", label: "start" }, { value: "middle", label: "middle" }, { value: "end", label: "end" }]

and 
in customBarChart.js
line 269 I add 
                step: measureInfo.step,

It seems to be OK

**Comment by WedersonCD** [comment]
Thaks for this feature
